apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: scada_prod
    user: postgres
    secureJsonData:
      password: postgres_pwd
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
