
listener 1883 0.0.0.0


# not in production
allow_anonymous true


# Persistance
persistence true
persistence_location /mosquitto/data/


# logs
log_dest stdout
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S


# connection 0 is unlimited
max_connections 100

# one client can 100 at a time
max_inflight_messages 100

# max queued msg for one cline
max_queued_messages 1000


# msg size limit 10mb
message_size_limit 1048576


# WEBSOCKET  Grafana Live 
# Grafana'nın MQTT Live paneli veya web tabanlı debug araçları için
# listener 9001
# protocol websockets


# PRODUCTION UPGRADE 

# 1. password file:
#    docker exec -it mqtt_broker_docker mosquitto_passwd -c /mosquitto/config/passwd bridge_user
#    docker exec -it mqtt_broker_docker mosquitto_passwd /mosquitto/config/passwd anomaly_user
#    docker exec -it mqtt_broker_docker mosquitto_passwd /mosquitto/config/passwd grafana_user
#
# 2. ACL (Access Control List) :
#    
# 3. add this to conf:
#    allow_anonymous false
#    password_file /mosquitto/config/passwd
#    acl_file /mosquitto/config/acl
#
# 4. TLS/SSL for certificate (Let's Encrypt or self-signed):
#    cafile   /mosquitto/certs/ca.crt
#    certfile /mosquitto/certs/server.crt
#    keyfile  /mosquitto/certs/server.key
#    tls_version tlsv1.3
# =============================================================================
